@startuml misGastos
class Gasto{
    -fecha: LocalDate
    -hora: LocalTime
    -monto: Int
    -descripcion: String
    -categoria: Categoria
    -comercio: Comercio   
}

class Comercio{}
class Categoria{
    -id: int

}

class Categorizador{
    - adapter: 
}

@enduml